### PR TITLE
fix: revert zk c client to 3.4.10 for compatibility

### PR DESCRIPTION
**Pull request by foreverneverer**
### What problem does this PR solve? 
Related issue: https://github.com/apache/incubator-pegasus/issues/1092

### What is changed and how does it work?

This pr revert zk c client to 3.4.10, this need merge into Pegasus 2.4:  https://github.com/apache/incubator-pegasus/issues/1032

##### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

##### Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note

### CODE REVIEW

**Review by acelyc111 — CHANGES_REQUESTED** [review]
Let’s disccus clearly before merging, thanks!

**Comment by foreverneverer** [comment]
> Let’s disccus clearly before merging, thanks!

OK, I hope it can be determined as soon as possible, because the release of 2.4 has been postponed for a long time. If it can't be solved, I hope this problem can be reconsidered after 2.4

**Comment by acelyc111** [comment]
> > Let’s disccus clearly before merging, thanks!
> 
> OK, I hope it can be determined as soon as possible, because the release of 2.4 has been postponed for a long time. If it can't be solved, I hope this problem can be reconsidered after 2.4

How about release 2.4 without this patch, and you can release an internal release or a other type of spcial release with this patch. In SensorsData we have tested with zk client 3.7.0 with zk server kerberos enabled and disabled, all works well as expected. And you guys also tested that in some product envs, I guess there may be some DNS issue in you mentioned "tjwq-test" env :)

**Review by acelyc111 — APPROVED** [review]

**Comment by acelyc111** [comment]
LGTM to merge it to branch 2.4.0

**Review by hycdong — APPROVED** [review]

**Pull request merged**
