### PR TITLE
build: require add issue reference in description using github action

### PR DESCRIPTION
**Pull request by Shuo-Jia**
### What problem does this PR solve? 
See  issue https://github.com/apache/incubator-pegasus/issues/869

## Side effects 

CI passed need you add issue ref like above URL in the later

### CODE REVIEW

**Review by Smityz — DISMISSED** [review]

**Comment by acelyc111** [comment]
not works, need to ask Apache infra admins to enable it
https://github.com/apache/incubator-pegasus/actions/runs/1662656033

**Comment by Shuo-Jia** [comment]
> not works, need to ask Apache infra admins to enable it https://github.com/apache/incubator-pegasus/actions/runs/1662656033

how to do？

**Comment by acelyc111** [comment]
> > not works, need to ask Apache infra admins to enable it https://github.com/apache/incubator-pegasus/actions/runs/1662656033
> 
> how to do？

like this: https://issues.apache.org/jira/browse/INFRA-22336

**Comment by Shuo-Jia** [comment]
I have submit jira to apache admins, mark as draft and wait jira  resolved

**Review by hycdong — APPROVED** [review]

**Review by Smityz — APPROVED** [review]

**Review by levy5307 — APPROVED** [review]

**Pull request merged**
