### PR TITLE
chore(clang-format): unify rdsn and Pegasus clang-format

### PR DESCRIPTION
**Pull request by acelyc111**
### What problem does this PR solve? 
Unify the rdsn and the Pegasus projects' clang-format tools since they are duplicated.

### What is changed and how does it work?
1. move .clang-format to the root path
2. update .github/workflows/lint_and_test_pegasus.yaml to lint all cpp files' style in Pegasus
3. remove lint job from .github/workflows/test_rdsn.yaml, and rename workflow. Same to rdsn/README.md.
4. update .licenserc.yaml, LICENSE, .rat-excludes since some license issues have been resolved, or files been removed.
6. remove lint files from rdsn: rdsn/run.sh, rdsn/scripts/linux/run-clang-format.sh
7. update lint files in Pegasus to lint all files in the repo: scripts/format_files.sh, scripts/run-clang-format.py
8. remove outdated files: scripts/travis.sh

### Checklist 

The workflow work well as expect. I submmit a patch with some code with bad style will be reported: https://github.com/apache/incubator-pegasus/runs/7097185266?check_suite_focus=true

### CODE REVIEW

**Review by levy5307 — APPROVED** [review]

**Review by foreverneverer — APPROVED** [review]

**Review by neverchanje — APPROVED** [review]
Lgtm

**Review by levy5307 — DISMISSED** [review]

**Review by neverchanje — APPROVED** [review]
Can it be merged now?

**Comment by acelyc111** [comment]
> Can it be merged now?

It will report an illegal instruction error if I don't skip building third party, as shown in https://github.com/apache/incubator-pegasus/runs/7209009710?check_suite_focus=true, I'm not sure how it happened, even I re-trigger rebuild the third party bin package.

**Comment by acelyc111** [comment]
> > Can it be merged now?
> 
> It will report an illegal instruction error if I don't skip building third party, as shown in https://github.com/apache/incubator-pegasus/runs/7209009710?check_suite_focus=true, I'm not sure how it happened, even I re-trigger rebuild the third party bin package.

So I remove --skip_thirdpary in .github/workflows/lint_and_test_pegasus.yaml

**Comment by acelyc111** [comment]
Let's merge this pr, the left issue is not introduced by this pr, we can resolve it latter.

**Review by foreverneverer — APPROVED** [review]

**Comment by acelyc111** [comment]
also related to: https://github.com/apache/incubator-pegasus/issues/1053

**Pull request merged**
